// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokemonShinyHuntingHelper.Data;

namespace PokemonShinyHuntingHelper.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20210223224414_AddedStartAndFinishTime")]
    partial class AddedStartAndFinishTime
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("PokemonShinyHuntingHelper.Data.Hunting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("Chain")
                        .HasColumnType("integer");

                    b.Property<int>("DexLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Finish")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Generation")
                        .HasColumnType("integer");

                    b.Property<double>("Odds")
                        .HasColumnType("double precision");

                    b.Property<string>("Pokemon")
                        .HasColumnType("text");

                    b.Property<bool>("ShinyCharm")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Hunting");
                });
#pragma warning restore 612, 618
        }
    }
}
